version: 2.1
orbs:
  node: circleci/node@1.1.6
  coverage-reporter: codacy/coverage-reporter@10.0.3
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - coverage-reporter/send_report:
          coverage-reports: 'coverage/lcov.info'
          project-token: ${CODACY_PROJECT_TOKEN}
workflows:
  build-and-test:
    jobs:
      - build-and-test
